- hosts: all
  become: yes

  tasks:
    - name: install system updates for centos systems
      yum: name=* state=present update_cache=yes
      when: ansible_distribution == "CentOS"

    - name: install system updates for ubuntu systems
      apt: upgrade=dist update_cache=yes
      when: ansible_distribution == "Ubuntu"
